In [1]:
import pandas as pd
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os
import matplotlib as mpl
mpl.use('TkAgg') 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
plt.ion()

In [2]:
def load_NSIN_data():
    df = pd.read_csv('../datasets/deviceCoordinates.csv')

    return df

In [3]:
coordinates = load_NSIN_data()

coordinates.head(n=5)

,Threat Id,Unnamed: 1,Unnamed: 2,Unnamed: 3,Latitude,Longitude,Altitude,Latitude(Predicted),Longitude(Predicted),Altitude(Predicted)
0,3784,NaN,NaN,NaN,42.491578,-71.311929,1263.0,42.493809,-71.308421,1370.0
1,3786,NaN,NaN,NaN,42.414375,-71.351943,10382.0,42.419018,-71.344386,10327.0
2,3726,NaN,NaN,NaN,42.770994,-71.986791,5065.0,42.774725,-71.983729,5027.0
3,3794,NaN,NaN,NaN,42.287262,-71.336343,3855.0,42.285045,-71.339763,3657.0
4,3797,NaN,NaN,NaN,42.321132,-71.247895,4228.0,42.319187,-71.252202,4244.0

In [4]:
coordinates = coordinates.drop('Unnamed: 1', inplace=False, axis=1)
coordinates = coordinates.drop('Unnamed: 2', inplace=False, axis=1)
coordinates = coordinates.drop('Unnamed: 3', inplace=False, axis=1)
coordinates

,Threat Id,Latitude,Longitude,Altitude,Latitude(Predicted),Longitude(Predicted),Altitude(Predicted)
0,3784,42.491578,-71.311929,1263.0,42.493809,-71.308421,1370.0
1,3786,42.414375,-71.351943,10382.0,42.419018,-71.344386,10327.0
2,3726,42.770994,-71.986791,5065.0,42.774725,-71.983729,5027.0
3,3794,42.287262,-71.336343,3855.0,42.285045,-71.339763,3657.0
4,3797,42.321132,-71.247895,4228.0,42.319187,-71.252202,4244.0
...,...,...,...,...,...,...,...
12796,3709,42.560154,-71.351636,4180.0,42.559939,-71.351395,4373.0
12797,4223,42.608898,-71.506995,4565.0,42.609121,-71.506041,4481.0
12798,4224,42.609692,-71.506976,4488.0,42.609915,-71.506022,4404.0
12799,4225,42.485592,-71.355463,1336.0,42.487193,-71.357921,1238.0
12800,4164,42.285726,-71.126203,7765.0,42.289145,-71.120698,8025.0

In [5]:
x = coordinates['Latitude']
y = coordinates['Longitude']
z = coordinates['Altitude']

fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(x,y,z,c='b', marker='o')

ax.set_xlabel('Latitude')
ax.set_ylabel('Longitude')
ax.set_zlabel('Altitude')

plt.show()

In [6]:
actual_latitude = x.to_numpy()
actual_longitude = y.to_numpy()
actual_altitude = z.to_numpy()


predicted_latitude = coordinates['Latitude(Predicted)'].to_numpy()
predicted_longitude= coordinates['Longitude(Predicted)'].to_numpy()
predicted_altitude= coordinates['Altitude(Predicted)'].to_numpy()

latitude_diff = actual_latitude - predicted_latitude
longitude_diff = actual_longitude - predicted_longitude
altitude_diff = actual_altitude - predicted_altitude
threat_id = coordinates['Threat Id'].to_numpy()

In [7]:
fig = plt.figure(figsize=(8,6))
plt.plot(actual_latitude,predicted_latitude, 'rx')
plt.xlabel('actual_latitude')
plt.ylabel('predicted_latitude')
plt.title('Latitude Difference')
plt.show()

In [8]:
fig = plt.figure(figsize=(8,6))
plt.plot(actual_longitude,predicted_longitude, 'rx')
plt.xlabel('actual_longitude')
plt.ylabel('predicted_longitude')
plt.title('Longitude Difference')
plt.show()

In [9]:
fig = plt.figure(figsize=(8,6))
plt.plot(actual_altitude,predicted_altitude,'rx')
plt.xlabel('actual_altitude')
plt.ylabel('predicted_altitude')
plt.title('Altitude Difference')
plt.show()

Predictions are near perfect as the graph is making a linear relationship with actual vs predicted.